menu:
  #Archives: /archives
  黄金屋: /favourite
  时光机: /favourite/time.html
  幻想间: /favourite/image.html
  关于我: /about
  
description: 
social:
  weibo: http://weibo.com/311512337
  github: https://github.com/cheng-peng

page_comment: true
logo: /images/avatar.png
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: 

google_analytics: UA-78918255-1
baidu_tongji: 9cdad07c755fa23f6aced510c6760e87
favicon: /images/avatar.png

#mathjax
mathjax: true

# 'Read more' button
excerpt_link: 继续阅读

# Footer message
site_license: 本站仅用来交流学习。
theme_message: <a href="http://hexo.io">程小鹏-个人博客</a> 

