# Blog info
blog_name: 程小鹏。
slogan: 心比天高。
url: http://www.cxp521.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/cxp.ico

# For seo
keywords: 程小鹏,前端,设计,前端开发,用户体验,AI,AE,PS,android,design,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Tags
    url: /tags
    target_blank: false #不在新页面打开
  - name: About
    url: /about
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/cxp521
    target_blank: true
  - name: Twitter
    url: https://twitter.com/CXP521
    target_blank: true

# config page nav
page_nav: 
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 标签
    url: /tags/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox: 
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 978515743@qq.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持CXP。
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 0521cef01e017f3e6f001042037af1bc

# Comment service
disqus_shortname: CXP
# duoshuo_shortname: forsigner


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "程小鹏，1995，Android."
    - "喜欢设计，擅长编程，喜欢睡懒觉."
    - "前端开发工程师，常用 HTML / CSS / JavaScript/Android."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@CXP"
    text_value_url: https://github.com/cxp521
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@程-小-鹏"
    text_value_url: http://weibo.com/u/311512337
  - type: qq
    icon: icon-qq
    text_key: QQ
    text_value: "qq"
    text_value_url: http://user.qzone.qq.com/978515743
  - type: location
    icon: icon-location
    text_value: 北京

link:
  - name: 暂无
    info: 身体和灵魂，总有一个在路上
    url: 
    avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100
  - name: 暂无
    info: 生命不止，折腾不息
    url: 
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
  - name: 暂无
    info: android ffmpeg nodejs gradle
    url: 
    avatar: https://avatars0.githubusercontent.com/u/2263785?v=3&s=100
  - name: 暂无
    info: 好记性不如烂笔头
    url: 
    avatar: https://avatars1.githubusercontent.com/u/1559563?v=3&s=100
  - name: 暂无
    info: FP, GUI, Writing
    url: 
    avatar: https://avatars2.githubusercontent.com/u/449224?v=3&s=100
  - name: 暂无
    info: Android成长分享
    url: 
    avatar: https://avatars1.githubusercontent.com/u/8677862?v=3&s=100

project:
  - type: personal
    name: CXP
    url: https://github.com/cxp21
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: beside
    url: https://github.com/forsigner/beside
    intro: I need you beside me
  - type: personal
    name: web-fontmin
    url: https://github.com/cxp521
    intro: 字体子集化，在线提取你需要的字体
  - type: personal
    name: magic-check
    url: https://github.com/cxp521
    intro: Beautify Radio and Checkbox with pure CSS
  - type: personal
    name: nice-bar
    url: https://github.com/cxp521
    intro: A nice and lightweight scrollbar
  - type: personal
    name: angular-nice-bar
    url: https://github.com/cxp521
    intro: A nice and lightweight scrollbar in Angular
  - type: personal
    name: fo-popover
    url: https://github.com/cxp521
    intro: A nice popover for Angular
  - type: personal
    name: fo-tooltip
    url: A nice tooltip for Angular
    intro: https://github.com/cxp521
  - type: personal
    name: fo-modal
    url: https://github.com/cxp521
    intro: A nice modal for Angular
  - type: personal
    name: mocer
    url: https://github.com/cxp521
    intro: Setup a mock server easily
  - type: personal
    name: node-pngdefry
    url: https://github.com/cxp521
    intro: Repairing iPhone fried PNGs using Node.js
  - type: personal
    name: ng-simditor
    url: https://github.com/cxp521
    intro: Angular directive for simditor
